### ISSUE TITLE
Secondary chord set

### ISSUE THREAD

**Issue by Lamera** [vojtechkral/bard#10]
Hello @vojtechkral !
Thank you very much for developing this project! It's exactly what I've been looking for a long time.
Now I try to build my first songbook and I can't get it to work with a secondary chord set. One `!-3` is working while transposing. As soon I set two `!!-3` it doesn't work anymore with the following error while generating the pdf:
`! Undefined control sequence.`

I'm running Ubuntu 22.04 with texlive-xelatex (latexmk).

**Comment by vojtechkral** [comment]
Probably a bug, I'll have a look...

**Comment by vojtechkral** [comment]
It's fixed in `main` now, thanks for reporting and glad you find the program useful.
Are you ok installing from `main`? If not I'll tag a release...

**Comment by Lamera** [comment]
Wow, that was fast!
Thank you so much. If you don't mind too much, it would be great to have a compiled build.
