### ISSUE TITLE
Multicol in bard 2.0

### ISSUE THREAD

**Issue by Lamera** [vojtechkral/bard#15]
Hello @vojtechkral !
I'm using your alpha release. Everything works great after adjusting the templates.
Except the multi column layout.
I get this error:
![grafik](https://user-images.githubusercontent.com/19840658/208307824-22a6129c-ecc0-4271-b687-f1b6ed6f46eb.png)

In the pdf.hbs I'm using the following code:
```hbs
\setlength{\columnsep}{15mm}
{{#*inline "h-columns"}}
\begin{absolutelynopagebreak}
\begin{multicols}{ {{~ num ~}} }
{{/inline}}

{{#*inline "h-/columns"}}
\end{multicols}
\end{absolutelynopagebreak}
{{/inline}}
```

And in the song itself I enclose the text between:
`<columns num=2>`
and
`</columns>`

Can you please help me to make it work?

**Comment by vojtechkral** [comment]
There needs to be a newline after the html tag, ie. instead of 

```md
 <columns num=2>
1. `C`Lyrics lyrics
```

it should be 
```md
 <columns num=2>

1. `C`Lyrics lyrics
```

... the issue is that in the first case the whole block gets parsed as HTML, these are commonmark parsing rules - not my decision...

**Comment by vojtechkral** [comment]
But I should fix the html parsing so that this is more obvious, or at least a bit less mysterious...

**Comment by Lamera** [comment]
Ahh, I see. The issue was that I used `<footnotesize>` right before the column html tag without a newline in between.

**Comment by vojtechkral** [comment]
Alterantively you can also put the tag on the same line as text, ie. `<footnotesize>Something something...` if you'd like it more compact...

**Comment by vojtechkral** [comment]
I've implemented a warning when this sort of thing happens, the warning hints that a blank line may be needed.
