### ISSUE TITLE
Does it support MacOS?

### ISSUE THREAD

**Issue by pengxiang-wang** [vojtechkral/bard#19]

**Comment by vojtechkral** [comment]
Hi. I have never tried running `bard` on a Mac, I don't own a Mac computer at the moment, so there isn't and "official" support with pre-built binaries and guidelines etc.

That being said, you can probably build `bard` yourself if you have the Rust toolchain and then if you install a TeX distribution suitable for Mac, it might just work.

**Comment by pengxiang-wang** [comment]
Thanks a lot!
