### ISSUE TITLE
2-column layout

### ISSUE THREAD

**Issue by vitSkalicky** [vojtechkral/bard#9]
Hello,
I'm using your amazing program to generate songbook of A4 paper size, which results in lots of wasted space on some pages. I would like to set some parts of certain songs that have short lines to be in 2 columns to save space.

For example Pověste ho vejš has a few short verses at the end that on my layout just don't fit onto single page. I want to put these into 2 columns so that they would fit.

```
# Pověste ho vejš
## Harlej

   Na dnešek jsem měl divnej sen
   slunce pálilo a před salonem
   stál v prachu dav, v tvářích cejch očekávání
   uprostřed šibenice z hrubých klád
   šerifův pomocník sejmul z hlavy odsouzenci kápi
   a dav zašuměl překvapením
   i já jsem zašuměl překvapením
   ten odsouzenec jsem byl já
   a šerif četl neúprosným hlasem rozsudek:

> Pověste ho `Ami`vejš, ať se houpá,
   pověste ho `C`vejš, ať má `G`dost.
   Pověste ho `Dmi`vejš, ať se `Ami`houpá,
   že tu `G`byl nezvanej `Ami`host.

1. Pověste ho, že byl jinej,
   že tu s námi dejchal stejnej vzduch.
   Pověste ho, ze byl línej
   a tak trochu dobrodruh.

2. Pověste ho za El Passo,
   za snídani v trávě a lodní zvon.
   Za to že neoplýval krásou,
   že měl `F`country rád, že se `E7`uměl smát i `Ami`vám.

### : 
   Nad hlav`C`ou mi slunce p`G`álí konec m`Dmi`ůj nic neodd`C`ál`G`í,
   do svejch `C`snů se dívám z `G`dáli.
   A do `Dmi`uší mi stále zní tahle `E7`moje píseň poslední

> Pověste ho vejš.... 

(2 columns begin)

3. Pověste ho za tu banku,
   v který zruinoval svůj vklad,
   za to že nikdy nevydržel
   na jednom místě stát. 

4. Pověste ho za tu jistou,
   který nesplnil svůj slib,
   že byl zarputilým optimistou
   a tak dělal spoustu chyb.

5. Pověste ho, že se koukal,
   a že hodně jed a hodně pil,
   že dal přednost jarním loukám
   a pak se oženil a pak se usadil a žil

### :
   Nad hlavou mi slunce pálí...
   
> Pověste ho vejš.... 

(2 columns end)
```

I've been thinking on how to mark it and my idea is to use three vertical lines followed by number of columns. Number of columns is reset at the end of each song. My proposal:

```
# Song title

1. single column

|||2
2. these verses will be
  typeset in 2 columns
3. In LaTeX multicols will be used
 in html I don't know yet
|||1
```

If the `|||1` wasn't used, 2-column layout would be terminated anyway because the song ends.

Another idea I had was to use `||>` to start 2-column layout and `||<` to end it instead.
```
# Song title

1. single column

||>
2. these verses will be
  typeset in 2 columns
3. In LaTeX multicols will be used
 in html I don't know yet
||<
```

I  would like to help on this as much as possible, but I have very little experience wirh rust.

**Comment by vojtechkral** [comment]
Ahoj,
interesting, yeah, I can see why you'd like two colums.
Not sure about the custom syntax though, I would like to stay as much in line with Markdown as possible.

One idea I've been thinking about for some time is support of TeX and HTML customizations from Markdown.
I thought this could be done with inline TeX/HTML code, but probably a better (more ergonomic) approach would be to let the user specifify custom inline blocks in the Hbs template, such as

```hbs
{{#*inline "foo"}} ... your custom TeX/HTML goes here ... {{/inline}}
```
and then 'call' that inline from markdown using some special syntax, such as `!foo` or `` `>foo` `` or something like that (I'd have to think about what's the best option here).
I think you could do various customizations including multicolumn layout this way.

I've been ignoring bard developement lately a little bit, but I plan to get back to it soon and this is one of the items on my TODO list.

**Comment by vojtechkral** [comment]
Actually, maybe the `[foo]` syntax should be used for these instead, that's standard markdown, it could be considered a special kind of link...

**Comment by vitSkalicky** [comment]
That sounds good, but simple `[foo]` might be accidentally triggered by a user, so I would rather use something like `[!foo]`, `!![foo]` or `[[foo]]`.

**Comment by vojtechkral** [comment]
Yeah, another option is to leverage the inline html feature of Markdown to do something like `<multicols>` ... stuff ... `</multicols>` .

I'll think about it, I've already started fixing some old bugs and willl do this next...

**Comment by vojtechkral** [comment]
@vitSkalicky I have implemented support for arbitrary extensions via HTML tags that are dispatched to Hbs inlines.
I decided to go with HTML tags because they are already supported in Markdown (no extensions needed) and can carry parameters.

This is unreleased yet, in my `dev` branch. To install from the `dev` branch, use:

    cargo install -f --git 'https://github.com/vojtechkral/bard.git' --branch dev

To use the feature, first add this generic code to your templates (this or similar will be part of templates when this stuff is relase):

```hbs
{{#*inline "b-html-block"}}
  {{~#each inlines}}{{> (lookup this "type") }}{{/each~}}
{{/inline}}
 
{{#*inline "i-tag"}}{{> (lookup this "name") attrs }}{{/inline}}
```

and then specifically for your use case, add something similar to this:

```hbs
\usepackage{multicol}

\setlength{\columnsep}{2cm}
{{#*inline "columns"}}\begin{multicols}{ {{~ num ~}} }{{/inline}}
{{#*inline "/columns"}}\end{multicols}{{/inline}}
```

And then from the Markdown, this is how you "call" those inlines:

```markdown

<columns num=2>

3. I went up to my chamber
All for to take a slumber
I dreamt of gold and jewels
And for sure 't was no wonder
But Jenny drew me charges
And she filled them up with water
Then sent for captain Farrell
To be ready for the slaughter
!>

4. 'Twas early in the morning
Just before I rose to travel
Up comes a band of footmen
And likewise captain Farrell
I first produced me pistol
For she stole away me rapier
I couldn't shoot the water
So a prisoner I was taken
!>

</columns>
```

Which should get you a result like this:

![2cols-example](https://user-images.githubusercontent.com/424891/167244749-1286469c-7f32-458f-9841-89ea9d084977.png)

(In this case the text is crammed quite a lot, because it's A5 paper, so it doesn't look very good, but if you use A4 it should probably look a lot better.)

I'm curious if it will work well for you :)

**Comment by vitSkalicky** [comment]
That's great. I have already been experimenting with columns in LaTeX a came up with code for decent columns:

Set up multicols with solid vertical ruler for improved readability:
```latex
\usepackage{multicol}

%% multicol style
\setlength{\columnsep}{25mm}
\setlength{\columnseprule}{0.4pt}
\def\columnseprulecolor{\color{black}}
```
Prevent page-break inside columns:
```LaTeX
%% Absoletely no page break - prevent page breaks in 2-column layouts
\newenvironment{absolutelynopagebreak}
  {\par\nobreak\vfil\penalty0\vfilneg
   \vtop\bgroup}
  {\par\xdef\tpd{\the\prevdepth}\egroup
   \prevdepth=\tpd}
```
Handlebars inlines:
```handlebars
{{#*inline "b-html-block"}}
  {{~#each inlines}}{{> (lookup this "type") }}{{/each~}}
{{/inline}}
 
{{#*inline "i-tag"}}{{> (lookup this "name") attrs }}{{/inline}}
   
{{#*inline "columns"}}
\begin{absolutelynopagebreak}
\begin{multicols}{ {{~ num ~}} }
{{/inline}}

{{#*inline "/columns"}}
\end{multicols}
\end{absolutelynopagebreak}
{{/inline}}
```

BTW I have also made an alphabetical ToC for my giant songbook (requires Arara). Should I make a PR?

**Comment by vojtechkral** [comment]
@vitSkalicky Cool, so from your point of view does the HTML feature solve the problem?
If so, I would document it and then spend some time with some other features, and eventually I'll make a new release.

> BTW I have also made an alphabetical ToC for my giant songbook (requires Arara). Should I make a PR?

You can do ToC with bard already using `bard utils sort-lines` (see [here](https://github.com/vojtechkral/bard/blob/main/doc/bard.toml.md#toc-sort-order)). It's a bit hacky but it works. Thank you for the offer but I don't think I would like to merge a solution that requires external tools...

**Comment by vitSkalicky** [comment]
Thanks, HTML solves my problem perfectly.
